# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb5a2f7bbfea6a4c683191fd9784e2509d2e08d5b037388efc6f0361b0d31530bcdbd2247a9bb9743817a7ec0711a71000a033a61c68c7aef618189c3eccc535

test:
  secret_key_base: 70ff86aef9789e7133da64bee551ee891add0ba7ec81ce53ab95b2c192cf0a71ae925f2501885ee42a4f4fea3c039122e8b23053f7af38010935f1bd9dcc0f9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
